# Generated by Django 4.1.5 on 2023-11-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=20)),
                ('adreca_fiscal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comanda', models.IntegerField()),
                ('data_creacio', models.DateField()),
                ('data_necessitat', models.DateField()),
                ('import_comanda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuari', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celra.client')),
            ],
        ),
        migrations.CreateModel(
            name='DetallVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('descripcio', models.TextField()),
                ('quantitat', models.IntegerField()),
                ('preu_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('import_total_linia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celra.comanda')),
            ],
        ),
    ]
